/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UniversityIdRouteImport } from './routes/university.$id'
import { Route as ApplyIdRouteImport } from './routes/apply.$id'
import { Route as ContactIdVideoRouteImport } from './routes/contact.$id.video'
import { Route as ContactIdChatRouteImport } from './routes/contact.$id.chat'
import { Route as ContactIdCallRouteImport } from './routes/contact.$id.call'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityIdRoute = UniversityIdRouteImport.update({
  id: '/university/$id',
  path: '/university/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyIdRoute = ApplyIdRouteImport.update({
  id: '/apply/$id',
  path: '/apply/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIdVideoRoute = ContactIdVideoRouteImport.update({
  id: '/contact/$id/video',
  path: '/contact/$id/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIdChatRoute = ContactIdChatRouteImport.update({
  id: '/contact/$id/chat',
  path: '/contact/$id/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIdCallRoute = ContactIdCallRouteImport.update({
  id: '/contact/$id/call',
  path: '/contact/$id/call',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/apply/$id': typeof ApplyIdRoute
  '/university/$id': typeof UniversityIdRoute
  '/contact/$id/call': typeof ContactIdCallRoute
  '/contact/$id/chat': typeof ContactIdChatRoute
  '/contact/$id/video': typeof ContactIdVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/apply/$id': typeof ApplyIdRoute
  '/university/$id': typeof UniversityIdRoute
  '/contact/$id/call': typeof ContactIdCallRoute
  '/contact/$id/chat': typeof ContactIdChatRoute
  '/contact/$id/video': typeof ContactIdVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/apply/$id': typeof ApplyIdRoute
  '/university/$id': typeof UniversityIdRoute
  '/contact/$id/call': typeof ContactIdCallRoute
  '/contact/$id/chat': typeof ContactIdChatRoute
  '/contact/$id/video': typeof ContactIdVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/profile'
    | '/schedule'
    | '/search'
    | '/apply/$id'
    | '/university/$id'
    | '/contact/$id/call'
    | '/contact/$id/chat'
    | '/contact/$id/video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/profile'
    | '/schedule'
    | '/search'
    | '/apply/$id'
    | '/university/$id'
    | '/contact/$id/call'
    | '/contact/$id/chat'
    | '/contact/$id/video'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/profile'
    | '/schedule'
    | '/search'
    | '/apply/$id'
    | '/university/$id'
    | '/contact/$id/call'
    | '/contact/$id/chat'
    | '/contact/$id/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  ProfileRoute: typeof ProfileRoute
  ScheduleRoute: typeof ScheduleRoute
  SearchRoute: typeof SearchRoute
  ApplyIdRoute: typeof ApplyIdRoute
  UniversityIdRoute: typeof UniversityIdRoute
  ContactIdCallRoute: typeof ContactIdCallRoute
  ContactIdChatRoute: typeof ContactIdChatRoute
  ContactIdVideoRoute: typeof ContactIdVideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university/$id': {
      id: '/university/$id'
      path: '/university/$id'
      fullPath: '/university/$id'
      preLoaderRoute: typeof UniversityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$id': {
      id: '/apply/$id'
      path: '/apply/$id'
      fullPath: '/apply/$id'
      preLoaderRoute: typeof ApplyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/$id/video': {
      id: '/contact/$id/video'
      path: '/contact/$id/video'
      fullPath: '/contact/$id/video'
      preLoaderRoute: typeof ContactIdVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/$id/chat': {
      id: '/contact/$id/chat'
      path: '/contact/$id/chat'
      fullPath: '/contact/$id/chat'
      preLoaderRoute: typeof ContactIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/$id/call': {
      id: '/contact/$id/call'
      path: '/contact/$id/call'
      fullPath: '/contact/$id/call'
      preLoaderRoute: typeof ContactIdCallRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  ProfileRoute: ProfileRoute,
  ScheduleRoute: ScheduleRoute,
  SearchRoute: SearchRoute,
  ApplyIdRoute: ApplyIdRoute,
  UniversityIdRoute: UniversityIdRoute,
  ContactIdCallRoute: ContactIdCallRoute,
  ContactIdChatRoute: ContactIdChatRoute,
  ContactIdVideoRoute: ContactIdVideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
