
ALTER TABLE public.universities
  ADD COLUMN IF NOT EXISTS type TEXT,
  ADD COLUMN IF NOT EXISTS accreditation TEXT,
  ADD COLUMN IF NOT EXISTS region TEXT,
  ADD COLUMN IF NOT EXISTS website TEXT,
  ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT false;

ALTER TABLE public.universities ALTER COLUMN tuition_min DROP NOT NULL;
ALTER TABLE public.universities ALTER COLUMN tuition_max DROP NOT NULL;

DELETE FROM public.universities;
DELETE FROM public.categories;

-- Categories per level
INSERT INTO public.categories (name, icon, education_level) VALUES
  ('Kedokteran','Stethoscope','UNIVERSITY'),
  ('Teknik','Cpu','UNIVERSITY'),
  ('Hukum','Scale','UNIVERSITY'),
  ('Ekonomi','Briefcase','UNIVERSITY'),
  ('Ilmu Komputer','Code','UNIVERSITY'),
  ('Farmasi','Beaker','UNIVERSITY'),
  ('Pertanian','Wheat','UNIVERSITY'),
  ('Psikologi','Brain','UNIVERSITY'),
  ('Pendidikan','GraduationCap','UNIVERSITY'),
  ('Bisnis','Building2','UNIVERSITY'),
  ('Komunikasi','MessageCircle','UNIVERSITY'),
  ('Desain','Palette','UNIVERSITY'),
  ('Arsitektur','Castle','UNIVERSITY'),
  ('Ilmu Agama','BookOpen','UNIVERSITY'),
  ('Early Literacy','BookOpen','TK'),
  ('Motor Skills','Activity','TK'),
  ('Parenting','Heart','TK'),
  ('Playful Learning','Sparkles','TK'),
  ('Creative Arts','Palette','TK'),
  ('Math Foundation','Calculator','SD'),
  ('Science Discovery','Microscope','SD'),
  ('Reading & Writing','BookOpen','SD'),
  ('Creative Arts','Palette','SD'),
  ('STEM & Robotics','Cpu','SMP'),
  ('Languages','Languages','SMP'),
  ('Coding Club','Code','SMP'),
  ('Sports','Trophy','SMP'),
  ('Science (IPA)','Microscope','SMA'),
  ('Social (IPS)','Users','SMA'),
  ('Vocational Tech','Wrench','SMA'),
  ('Scholarship Pipeline','Trophy','SMA');

-- Universities
INSERT INTO public.universities (name, location, country, global_ranking, rating, reviews_count, tuition_min, tuition_max, image_url, description, programs, category, is_popular, education_level, type, accreditation, region, website, is_featured) VALUES
('Universitas Indonesia (UI)','Depok, Jawa Barat','Indonesia',1,4.9,1200,null,null,null,'PTN terkemuka di Indonesia.',ARRAY['Kedokteran','Hukum','Teknik','Ekonomi','Psikologi','Ilmu Komputer','Farmasi','Keperawatan'],'Kedokteran',true,'UNIVERSITY','Negeri (PTN)','Unggul','Jawa','ui.ac.id',false),
('Institut Teknologi Bandung (ITB)','Bandung, Jawa Barat','Indonesia',2,4.9,1100,null,null,null,'Kampus teknik & sains terdepan.',ARRAY['Teknik Informatika','Teknik Elektro','Arsitektur','Matematika','Fisika','Teknik Kimia'],'Teknik',true,'UNIVERSITY','Negeri (PTN)','Unggul','Jawa','itb.ac.id',false),
('Universitas Gadjah Mada (UGM)','Yogyakarta, DIY','Indonesia',3,4.9,1300,null,null,null,'Universitas terbesar di DIY.',ARRAY['Kedokteran','Hukum','Pertanian','Ekonomi','Teknik','Psikologi','Farmasi'],'Kedokteran',true,'UNIVERSITY','Negeri (PTN)','Unggul','Jawa','ugm.ac.id',false),
('Universitas Airlangga (UNAIR)','Surabaya, Jawa Timur','Indonesia',4,4.8,900,null,null,null,null,ARRAY['Kedokteran','Farmasi','Keperawatan','Hukum','Ekonomi','Psikologi'],'Kedokteran',true,'UNIVERSITY','Negeri (PTN)','Unggul','Jawa','unair.ac.id',false),
('Institut Pertanian Bogor (IPB)','Bogor, Jawa Barat','Indonesia',5,4.8,850,null,null,null,null,ARRAY['Pertanian','Kehutanan','Peternakan','Teknologi Pangan','Ilmu Komputer'],'Pertanian',true,'UNIVERSITY','Negeri (PTN)','Unggul','Jawa','ipb.ac.id',false),
('Universitas Diponegoro (UNDIP)','Semarang, Jawa Tengah','Indonesia',6,4.7,820,null,null,null,null,ARRAY['Teknik','Hukum','Ekonomi','Kedokteran','Ilmu Sosial','Perikanan'],'Teknik',false,'UNIVERSITY','Negeri (PTN)','Unggul','Jawa','undip.ac.id',false),
('Universitas Brawijaya (UB)','Malang, Jawa Timur','Indonesia',7,4.7,800,null,null,null,null,ARRAY['Pertanian','Teknik','Ekonomi','Hukum','Kedokteran','Ilmu Komputer'],'Pertanian',false,'UNIVERSITY','Negeri (PTN)','Unggul','Jawa','ub.ac.id',false),
('Universitas Padjadjaran (UNPAD)','Bandung, Jawa Barat','Indonesia',8,4.7,780,null,null,null,null,ARRAY['Kedokteran','Hukum','Ekonomi','Komunikasi','Farmasi','Psikologi'],'Kedokteran',false,'UNIVERSITY','Negeri (PTN)','Unggul','Jawa','unpad.ac.id',false),
('Universitas Hasanuddin (UNHAS)','Makassar, Sulawesi Selatan','Indonesia',9,4.7,720,null,null,null,null,ARRAY['Kedokteran','Teknik','Hukum','Ekonomi','Pertanian','Ilmu Sosial'],'Kedokteran',false,'UNIVERSITY','Negeri (PTN)','Unggul','Sulawesi','unhas.ac.id',false),
('Universitas Sebelas Maret (UNS)','Surakarta, Jawa Tengah','Indonesia',10,4.6,700,null,null,null,null,ARRAY['Teknik','Ekonomi','Hukum','Kedokteran','Pertanian','Seni'],'Teknik',false,'UNIVERSITY','Negeri (PTN)','Unggul','Jawa','uns.ac.id',false),
('Universitas Pendidikan Indonesia (UPI)','Bandung, Jawa Barat','Indonesia',11,4.6,690,null,null,null,null,ARRAY['Pendidikan','Psikologi','Ekonomi','Teknik','Ilmu Komputer'],'Pendidikan',false,'UNIVERSITY','Negeri (PTN)','Unggul','Jawa','upi.edu',false),
('Universitas Negeri Yogyakarta (UNY)','Yogyakarta, DIY','Indonesia',12,4.6,650,null,null,null,null,ARRAY['Pendidikan','Teknik','Ekonomi','Olahraga','Seni'],'Pendidikan',false,'UNIVERSITY','Negeri (PTN)','Unggul','Jawa','uny.ac.id',false),
('Institut Teknologi Sepuluh Nopember (ITS)','Surabaya, Jawa Timur','Indonesia',13,4.7,750,null,null,null,null,ARRAY['Teknik Informatika','Teknik Elektro','Teknik Sipil','Desain','Matematika'],'Teknik',true,'UNIVERSITY','Negeri (PTN)','Unggul','Jawa','its.ac.id',false),
('Universitas Syiah Kuala (USK)','Banda Aceh, Aceh','Indonesia',14,4.5,500,null,null,null,null,ARRAY['Kedokteran','Teknik','Hukum','Ekonomi','Pertanian'],'Kedokteran',false,'UNIVERSITY','Negeri (PTN)','Baik Sekali','Sumatera','usk.ac.id',false),
('Universitas Sumatera Utara (USU)','Medan, Sumatera Utara','Indonesia',15,4.5,600,null,null,null,null,ARRAY['Kedokteran','Teknik','Hukum','Ekonomi','Pertanian','Farmasi'],'Kedokteran',false,'UNIVERSITY','Negeri (PTN)','Baik Sekali','Sumatera','usu.ac.id',false),
('Universitas Andalas (UNAND)','Padang, Sumatera Barat','Indonesia',16,4.5,520,null,null,null,null,ARRAY['Kedokteran','Teknik','Pertanian','Hukum','Ekonomi'],'Kedokteran',false,'UNIVERSITY','Negeri (PTN)','Baik Sekali','Sumatera','unand.ac.id',false),
('Universitas Lampung (UNILA)','Bandar Lampung, Lampung','Indonesia',17,4.4,420,null,null,null,null,ARRAY['Teknik','Hukum','Ekonomi','Pertanian','Ilmu Sosial','Kedokteran'],'Teknik',false,'UNIVERSITY','Negeri (PTN)','Baik Sekali','Sumatera','unila.ac.id',false),
('Universitas Sriwijaya (UNSRI)','Palembang, Sumatera Selatan','Indonesia',18,4.4,460,null,null,null,null,ARRAY['Teknik','Hukum','Ekonomi','Kedokteran','Pertanian','Ilmu Komputer'],'Teknik',false,'UNIVERSITY','Negeri (PTN)','Baik Sekali','Sumatera','unsri.ac.id',false),
('Universitas Tanjungpura (UNTAN)','Pontianak, Kalimantan Barat','Indonesia',19,4.4,400,null,null,null,null,ARRAY['Teknik','Hukum','Ekonomi','Pertanian','Kehutanan','Ilmu Sosial'],'Teknik',false,'UNIVERSITY','Negeri (PTN)','Baik Sekali','Kalimantan','untan.ac.id',false),
('Universitas Mulawarman (UNMUL)','Samarinda, Kalimantan Timur','Indonesia',20,4.4,410,null,null,null,null,ARRAY['Teknik','Kehutanan','Pertanian','Ekonomi','Hukum','Ilmu Komputer'],'Teknik',false,'UNIVERSITY','Negeri (PTN)','Baik Sekali','Kalimantan','unmul.ac.id',false),
('Universitas Lambung Mangkurat (ULM)','Banjarmasin, Kalimantan Selatan','Indonesia',21,4.4,430,null,null,null,null,ARRAY['Kedokteran','Teknik','Hukum','Pertanian','Ekonomi','Kehutanan'],'Kedokteran',true,'UNIVERSITY','Negeri (PTN)','Baik Sekali','Kalimantan','ulm.ac.id',false),
('Universitas Palangka Raya (UPR)','Palangka Raya, Kalimantan Tengah','Indonesia',22,4.3,350,null,null,null,null,ARRAY['Pertanian','Kehutanan','Teknik','Ekonomi','Hukum','Ilmu Sosial'],'Pertanian',false,'UNIVERSITY','Negeri (PTN)','Baik Sekali','Kalimantan','upr.ac.id',false),
('Universitas Sam Ratulangi (UNSRAT)','Manado, Sulawesi Utara','Indonesia',23,4.4,380,null,null,null,null,ARRAY['Kedokteran','Teknik','Hukum','Ekonomi','Pertanian','Perikanan'],'Kedokteran',false,'UNIVERSITY','Negeri (PTN)','Baik Sekali','Sulawesi','unsrat.ac.id',false),
('Universitas Tadulako (UNTAD)','Palu, Sulawesi Tengah','Indonesia',24,4.3,340,null,null,null,null,ARRAY['Teknik','Hukum','Ekonomi','Pertanian','Kedokteran','Ilmu Sosial'],'Teknik',false,'UNIVERSITY','Negeri (PTN)','Baik Sekali','Sulawesi','untad.ac.id',false),
('Universitas Halu Oleo (UHO)','Kendari, Sulawesi Tenggara','Indonesia',25,4.3,330,null,null,null,null,ARRAY['Teknik','Pertanian','Hukum','Ekonomi','Perikanan','Ilmu Sosial'],'Teknik',false,'UNIVERSITY','Negeri (PTN)','Baik Sekali','Sulawesi','uho.ac.id',false),
('Universitas Mataram (UNRAM)','Mataram, NTB','Indonesia',26,4.3,320,null,null,null,null,ARRAY['Teknik','Pertanian','Hukum','Ekonomi','Kedokteran','Peternakan'],'Teknik',false,'UNIVERSITY','Negeri (PTN)','Baik Sekali','Bali & NTB','unram.ac.id',false),
('Universitas Udayana (UNUD)','Denpasar, Bali','Indonesia',27,4.5,560,null,null,null,null,ARRAY['Kedokteran','Teknik','Hukum','Pariwisata','Pertanian','Ekonomi'],'Kedokteran',true,'UNIVERSITY','Negeri (PTN)','Unggul','Bali & NTB','unud.ac.id',false),
('Universitas Nusa Cendana (UNDANA)','Kupang, NTT','Indonesia',28,4.2,280,null,null,null,null,ARRAY['Teknik','Pertanian','Hukum','Ekonomi','Peternakan','Ilmu Sosial'],'Teknik',false,'UNIVERSITY','Negeri (PTN)','Baik','NTT & Papua','undana.ac.id',false),
('Universitas Cenderawasih (UNCEN)','Jayapura, Papua','Indonesia',29,4.2,260,null,null,null,null,ARRAY['Teknik','Hukum','Ekonomi','Pertanian','Ilmu Sosial','Kedokteran'],'Teknik',false,'UNIVERSITY','Negeri (PTN)','Baik','NTT & Papua','uncen.ac.id',false),
('Universitas Pattimura (UNPATTI)','Ambon, Maluku','Indonesia',30,4.3,290,null,null,null,null,ARRAY['Teknik','Hukum','Ekonomi','Pertanian','Perikanan','Ilmu Sosial'],'Teknik',false,'UNIVERSITY','Negeri (PTN)','Baik Sekali','Maluku','unpatti.ac.id',false),
('Universitas Bina Nusantara (BINUS)','Jakarta, DKI Jakarta','Indonesia',31,4.7,950,null,null,null,null,ARRAY['Teknik Informatika','Sistem Informasi','Desain','Bisnis','Komunikasi','Akuntansi'],'Ilmu Komputer',true,'UNIVERSITY','Swasta (PTS)','Unggul','Jawa','binus.ac.id',false),
('Universitas Pelita Harapan (UPH)','Tangerang, Banten','Indonesia',32,4.6,720,null,null,null,null,ARRAY['Kedokteran','Hukum','Teknik','Bisnis','Komunikasi','Desain'],'Kedokteran',false,'UNIVERSITY','Swasta (PTS)','Unggul','Jawa','uph.edu',false),
('Universitas Atma Jaya Yogyakarta (UAJY)','Yogyakarta, DIY','Indonesia',33,4.5,520,null,null,null,null,ARRAY['Teknik','Hukum','Ekonomi','Arsitektur','Ilmu Komunikasi','Bioteknologi'],'Teknik',false,'UNIVERSITY','Swasta (PTS)','Unggul','Jawa','uajy.ac.id',false),
('Universitas Muhammadiyah Yogyakarta (UMY)','Yogyakarta, DIY','Indonesia',34,4.5,510,null,null,null,null,ARRAY['Kedokteran','Teknik','Hukum','Ekonomi','Ilmu Sosial','Farmasi'],'Kedokteran',false,'UNIVERSITY','Swasta (PTS)','Unggul','Jawa','umy.ac.id',false),
('Universitas Islam Indonesia (UII)','Yogyakarta, DIY','Indonesia',35,4.5,540,null,null,null,null,ARRAY['Hukum','Teknik','Ekonomi','Psikologi','Kedokteran','Ilmu Agama'],'Hukum',false,'UNIVERSITY','Swasta (PTS)','Unggul','Jawa','uii.ac.id',false),
('Universitas Telkom (Tel-U)','Bandung, Jawa Barat','Indonesia',36,4.6,680,null,null,null,null,ARRAY['Teknik Informatika','Sistem Informasi','Teknik Elektro','Desain','Bisnis','Komunikasi'],'Ilmu Komputer',true,'UNIVERSITY','Swasta (PTS)','Unggul','Jawa','telkomuniversity.ac.id',false),
('Universitas Muhammadiyah Malang (UMM)','Malang, Jawa Timur','Indonesia',37,4.5,490,null,null,null,null,ARRAY['Teknik','Ekonomi','Hukum','Kedokteran','Psikologi','Ilmu Sosial'],'Teknik',false,'UNIVERSITY','Swasta (PTS)','Unggul','Jawa','umm.ac.id',false),
('Universitas Mercu Buana (UMB)','Jakarta, DKI Jakarta','Indonesia',38,4.4,440,null,null,null,null,ARRAY['Teknik','Ekonomi','Desain','Komunikasi','Psikologi','Ilmu Komputer'],'Teknik',false,'UNIVERSITY','Swasta (PTS)','Baik Sekali','Jawa','mercubuana.ac.id',false),
('Universitas Tarumanagara (UNTAR)','Jakarta, DKI Jakarta','Indonesia',39,4.4,460,null,null,null,null,ARRAY['Kedokteran','Teknik','Hukum','Ekonomi','Psikologi','Desain'],'Kedokteran',false,'UNIVERSITY','Swasta (PTS)','Baik Sekali','Jawa','untar.ac.id',false),
('Universitas Trisakti','Jakarta, DKI Jakarta','Indonesia',40,4.4,470,null,null,null,null,ARRAY['Kedokteran','Teknik','Hukum','Ekonomi','Arsitektur','Ilmu Komunikasi'],'Kedokteran',false,'UNIVERSITY','Swasta (PTS)','Baik Sekali','Jawa','trisakti.ac.id',false),
('Universitas Islam Negeri (UIN) Jakarta','Jakarta, DKI Jakarta','Indonesia',41,4.5,500,null,null,null,null,ARRAY['Ilmu Agama','Hukum','Ekonomi','Dakwah','Ilmu Sosial','Kedokteran'],'Ilmu Agama',false,'UNIVERSITY','Negeri (PTN)','Unggul','Jawa','uinjkt.ac.id',false),
('Universitas Islam Negeri (UIN) Malang','Malang, Jawa Timur','Indonesia',42,4.4,440,null,null,null,null,ARRAY['Ilmu Agama','Hukum','Ekonomi','Psikologi','Teknik','Ilmu Sosial'],'Ilmu Agama',false,'UNIVERSITY','Negeri (PTN)','Unggul','Jawa','uin-malang.ac.id',false),
('Universitas Negeri Makassar (UNM)','Makassar, Sulawesi Selatan','Indonesia',43,4.4,420,null,null,null,null,ARRAY['Pendidikan','Teknik','Ekonomi','Olahraga','Seni','Ilmu Sosial'],'Pendidikan',false,'UNIVERSITY','Negeri (PTN)','Baik Sekali','Sulawesi','unm.ac.id',false),
('Universitas Negeri Surabaya (UNESA)','Surabaya, Jawa Timur','Indonesia',44,4.4,430,null,null,null,null,ARRAY['Pendidikan','Teknik','Ekonomi','Olahraga','Seni','Ilmu Sosial'],'Pendidikan',false,'UNIVERSITY','Negeri (PTN)','Baik Sekali','Jawa','unesa.ac.id',false),
('Universitas Negeri Semarang (UNNES)','Semarang, Jawa Tengah','Indonesia',45,4.4,425,null,null,null,null,ARRAY['Pendidikan','Teknik','Ekonomi','Olahraga','Hukum','Ilmu Sosial'],'Pendidikan',false,'UNIVERSITY','Negeri (PTN)','Baik Sekali','Jawa','unnes.ac.id',false),
('Universitas Jember (UNEJ)','Jember, Jawa Timur','Indonesia',46,4.4,410,null,null,null,null,ARRAY['Pertanian','Teknik','Hukum','Ekonomi','Kedokteran','Farmasi'],'Pertanian',false,'UNIVERSITY','Negeri (PTN)','Baik Sekali','Jawa','unej.ac.id',false),
('Universitas Riau (UNRI)','Pekanbaru, Riau','Indonesia',47,4.3,360,null,null,null,null,ARRAY['Teknik','Hukum','Ekonomi','Pertanian','Perikanan','Ilmu Sosial'],'Teknik',false,'UNIVERSITY','Negeri (PTN)','Baik Sekali','Sumatera','unri.ac.id',false),
('Universitas Jambi (UNJA)','Jambi, Jambi','Indonesia',48,4.3,310,null,null,null,null,ARRAY['Pertanian','Teknik','Hukum','Ekonomi','Peternakan','Ilmu Sosial'],'Pertanian',false,'UNIVERSITY','Negeri (PTN)','Baik Sekali','Sumatera','unja.ac.id',false),
('Universitas Bengkulu (UNIB)','Bengkulu, Bengkulu','Indonesia',49,4.3,300,null,null,null,null,ARRAY['Pertanian','Teknik','Hukum','Ekonomi','Ilmu Sosial','Matematika'],'Pertanian',false,'UNIVERSITY','Negeri (PTN)','Baik Sekali','Sumatera','unib.ac.id',false),
('Universitas Borneo Lestari (UNBL)','Banjarbaru, Kalimantan Selatan','Indonesia',50,4.4,260,null,null,null,'Kampus unggulan di Kalimantan Selatan.',ARRAY['Manajemen','Farmasi','Teknik Informatika','Akuntansi','Ilmu Hukum','Kesehatan Masyarakat'],'Bisnis',true,'UNIVERSITY','Swasta (PTS)','Baik Sekali','Kalimantan','unbl.ac.id',true);

-- Schools
INSERT INTO public.universities (name, location, country, rating, reviews_count, image_url, programs, category, is_popular, education_level, type, accreditation, region, is_featured) VALUES
('TK Islam Terpadu Nurul Fikri','Jakarta Selatan, DKI Jakarta','Indonesia',4.9,210,null,ARRAY['Early Literacy','Motor Skills','Parenting'],'Early Literacy',true,'TK','Swasta Islam','Unggul','Jawa',false),
('TK Labschool Jakarta','Jakarta Timur, DKI Jakarta','Indonesia',4.8,190,null,ARRAY['Playful Learning','Early Literacy','Motor Skills'],'Playful Learning',true,'TK','Swasta','Unggul','Jawa',false),
('TK Al-Azhar 1','Jakarta Selatan, DKI Jakarta','Indonesia',4.8,180,null,ARRAY['Early Literacy','Parenting','Motor Skills'],'Early Literacy',true,'TK','Swasta Islam','Unggul','Jawa',false),
('TK Negeri Pembina Banjarbaru','Banjarbaru, Kalimantan Selatan','Indonesia',4.7,150,null,ARRAY['Early Literacy','Motor Skills','Playful Learning'],'Early Literacy',true,'TK','Negeri','Baik Sekali','Kalimantan',false),
('TK Islam Sabilal Muhtadin','Banjarmasin, Kalimantan Selatan','Indonesia',4.7,160,null,ARRAY['Early Literacy','Parenting','Motor Skills'],'Early Literacy',false,'TK','Swasta Islam','Baik Sekali','Kalimantan',false),
('TK Kristen Kalam Kudus','Surabaya, Jawa Timur','Indonesia',4.7,140,null,ARRAY['Playful Learning','Motor Skills','Creative Arts'],'Creative Arts',false,'TK','Swasta Kristen','Baik Sekali','Jawa',false),
('TK Budi Mulia Dua','Yogyakarta, DIY','Indonesia',4.8,170,null,ARRAY['Early Literacy','Motor Skills','Playful Learning'],'Early Literacy',false,'TK','Swasta','Unggul','Jawa',false),
('TK Global Mandiri','Bekasi, Jawa Barat','Indonesia',4.7,130,null,ARRAY['Early Literacy','Parenting','Motor Skills'],'Early Literacy',false,'TK','Swasta','Baik Sekali','Jawa',false),

('SD Labschool Kebayoran','Jakarta Selatan, DKI Jakarta','Indonesia',4.9,260,null,ARRAY['Math Foundation','Science Discovery','Creative Arts'],'Math Foundation',true,'SD','Swasta','Unggul','Jawa',false),
('SD Islam Al-Azhar 1','Jakarta Selatan, DKI Jakarta','Indonesia',4.8,240,null,ARRAY['Reading & Writing','Math Foundation','Science Discovery'],'Reading & Writing',true,'SD','Swasta Islam','Unggul','Jawa',false),
('SD Negeri Sudirman 1','Makassar, Sulawesi Selatan','Indonesia',4.7,200,null,ARRAY['Math Foundation','Reading & Writing','Science Discovery'],'Math Foundation',false,'SD','Negeri','Baik Sekali','Sulawesi',false),
('SD Cendekia Muda','Banjarbaru, Kalimantan Selatan','Indonesia',4.7,150,null,ARRAY['Math Foundation','Science Discovery','Creative Arts'],'Math Foundation',true,'SD','Swasta','Baik Sekali','Kalimantan',false),
('SD Islam Terpadu Ukhuwah','Banjarmasin, Kalimantan Selatan','Indonesia',4.8,170,null,ARRAY['Reading & Writing','Math Foundation','Science Discovery'],'Reading & Writing',false,'SD','Swasta Islam','Unggul','Kalimantan',false),
('SD Kristen Kalam Kudus','Surakarta, Jawa Tengah','Indonesia',4.7,160,null,ARRAY['Math Foundation','Science Discovery','Creative Arts'],'Math Foundation',false,'SD','Swasta Kristen','Baik Sekali','Jawa',false),
('SD Negeri Percobaan 1','Yogyakarta, DIY','Indonesia',4.7,180,null,ARRAY['Reading & Writing','Math Foundation','Science Discovery'],'Reading & Writing',false,'SD','Negeri','Baik Sekali','Jawa',false),
('SD Global Mandiri','Bekasi, Jawa Barat','Indonesia',4.8,190,null,ARRAY['Math Foundation','Science Discovery','Creative Arts'],'Math Foundation',false,'SD','Swasta','Unggul','Jawa',false),

('SMP Negeri 8 Jakarta','Jakarta Pusat, DKI Jakarta','Indonesia',4.9,310,null,ARRAY['STEM & Robotics','Languages','Coding Club'],'STEM & Robotics',true,'SMP','Negeri','Unggul','Jawa',false),
('SMP Labschool Kebayoran','Jakarta Selatan, DKI Jakarta','Indonesia',4.8,280,null,ARRAY['STEM & Robotics','Sports','Coding Club'],'STEM & Robotics',true,'SMP','Swasta','Unggul','Jawa',false),
('SMP Islam Al-Azhar 1','Jakarta Selatan, DKI Jakarta','Indonesia',4.8,260,null,ARRAY['Languages','STEM & Robotics','Sports'],'Languages',false,'SMP','Swasta Islam','Unggul','Jawa',false),
('SMP Negeri 1 Banjarbaru','Banjarbaru, Kalimantan Selatan','Indonesia',4.7,200,null,ARRAY['STEM & Robotics','Sports','Languages'],'STEM & Robotics',true,'SMP','Negeri','Baik Sekali','Kalimantan',false),
('SMP Islam Sabilal Muhtadin','Banjarmasin, Kalimantan Selatan','Indonesia',4.7,180,null,ARRAY['Languages','STEM & Robotics','Coding Club'],'Languages',false,'SMP','Swasta Islam','Baik Sekali','Kalimantan',false),
('SMP Negeri 5 Surabaya','Surabaya, Jawa Timur','Indonesia',4.8,240,null,ARRAY['STEM & Robotics','Sports','Languages'],'STEM & Robotics',false,'SMP','Negeri','Unggul','Jawa',false),
('SMP Stella Duce 1','Yogyakarta, DIY','Indonesia',4.7,200,null,ARRAY['Languages','Sports','Coding Club'],'Languages',false,'SMP','Swasta Katolik','Baik Sekali','Jawa',false),
('SMP Global Sevilla','Jakarta Barat, DKI Jakarta','Indonesia',4.8,220,null,ARRAY['STEM & Robotics','Languages','Sports'],'STEM & Robotics',false,'SMP','International','Unggul','Jawa',false),

('SMA Negeri 8 Jakarta','Jakarta Selatan, DKI Jakarta','Indonesia',4.9,360,null,ARRAY['Science (IPA)','Social (IPS)','Scholarship Pipeline'],'Science (IPA)',true,'SMA','Negeri','Unggul','Jawa',false),
('SMA Negeri 3 Bandung','Bandung, Jawa Barat','Indonesia',4.9,340,null,ARRAY['Science (IPA)','Social (IPS)','Scholarship Pipeline'],'Science (IPA)',true,'SMA','Negeri','Unggul','Jawa',false),
('SMA Kanisius','Jakarta Pusat, DKI Jakarta','Indonesia',4.8,290,null,ARRAY['Science (IPA)','Social (IPS)','Scholarship Pipeline'],'Science (IPA)',true,'SMA','Swasta Katolik','Unggul','Jawa',false),
('SMA Negeri 1 Banjarbaru','Banjarbaru, Kalimantan Selatan','Indonesia',4.8,210,null,ARRAY['Science (IPA)','Social (IPS)','Scholarship Pipeline'],'Science (IPA)',true,'SMA','Negeri','Unggul','Kalimantan',false),
('SMA Islam Sabilal Muhtadin','Banjarmasin, Kalimantan Selatan','Indonesia',4.7,190,null,ARRAY['Social (IPS)','Science (IPA)','Scholarship Pipeline'],'Social (IPS)',false,'SMA','Swasta Islam','Baik Sekali','Kalimantan',false),
('SMK Negeri 1 Jakarta','Jakarta Pusat, DKI Jakarta','Indonesia',4.8,260,null,ARRAY['Vocational Tech','Science (IPA)','Scholarship Pipeline'],'Vocational Tech',false,'SMA','Negeri','Unggul','Jawa',false),
('SMA Negeri 1 Yogyakarta','Yogyakarta, DIY','Indonesia',4.8,280,null,ARRAY['Science (IPA)','Social (IPS)','Scholarship Pipeline'],'Science (IPA)',false,'SMA','Negeri','Unggul','Jawa',false),
('SMK Telkom Malang','Malang, Jawa Timur','Indonesia',4.8,250,null,ARRAY['Vocational Tech','Coding Club','Science (IPA)'],'Vocational Tech',true,'SMA','Swasta','Unggul','Jawa',false),
('SMA Negeri 1 Makassar','Makassar, Sulawesi Selatan','Indonesia',4.7,230,null,ARRAY['Science (IPA)','Social (IPS)','Scholarship Pipeline'],'Science (IPA)',false,'SMA','Negeri','Baik Sekali','Sulawesi',false),
('SMA Negeri 1 Surabaya','Surabaya, Jawa Timur','Indonesia',4.8,270,null,ARRAY['Science (IPA)','Social (IPS)','Scholarship Pipeline'],'Science (IPA)',false,'SMA','Negeri','Unggul','Jawa',false);
